# Generated by Django 5.1.5 on 2025-01-21 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveyapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientdata',
            name='cough_attack',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name="Yo'tal xuruji"),
        ),
        migrations.AlterField(
            model_name='patientdata',
            name='what_sputum',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name="Qanday balg'am"),
        ),
        migrations.AlterField(
            model_name='patientdata',
            name='what_suffocation',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Qanday xansirash'),
        ),
        migrations.AlterField(
            model_name='patientdata',
            name='what_temperature',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Qanday harorat'),
        ),
    ]
